
### 상품리스트 가져오기
GET http://localhost:8000/api/products

### 특정 유저(accessToken)의 정보 가져오기(패스워드 제외)
GET http://localhost:8000/api/users/me

### 로그아웃
GET http://localhost:8000/api/auth/signout

### 네비게이션에 나열할 카테고리 리스트 가져오기
GET http://localhost:8000/api/categories

### 특정 유저(accessToken)의 장바구니 데이터 가져오기
GET http://localhost:8000/api/carts

### 특정 유저(accessToken)의 관심상품 리스트 가져오기
GET http://localhost:8000/api/favorites

### 주문하기
GET http://localhost:8000/api/order

### 결제하기
GET http://localhost:8000/api/order/pay

### 특정 유저(accessToken)의 관심상품 추가/제거(관심상품 추가, 상품의 좋아요 개수 증가 / 관심상품 제거, 상품의 좋아요 개수 감소)
POST http://localhost:8000/api/favorites
content-type: application/json

{ "id" : 1 }

### 회원가입시 이메일 중복 확인
POST http://localhost:8000/api/auth/signup/check
content-type: application/json

// { "email" : "test@test.com" }
{ "email" : "new@new.com" }

### 장바구니에 상품 추가
POST http://localhost:8000/api/carts/5
content-type: application/json

// { "selectedSize" : 260, "quantity" : 1 }
{ "selectedSize" : 255, "quantity" : 10 }

### 로그인 기능
POST http://localhost:8000/api/auth/signin
content-type: application/json

{ "email": "test@test.com", "password": "test123"}

### 장바구니 사이즈(고정), 수량 변경
PATCH http://localhost:8000/api/carts/3
content-type: application/json

{ "quantity" : 1 }
//{ "quantity" : 20 }


### 장바구니 특정 상품 삭제
DELETE http://localhost:8000/api/carts/3
content-type: application/json